index.js
test.js

This change will enable https://github.com/elastic/apm-agent-nodejs/issues/210.

Add serverTimeout option

---

README.md
package.json

chore: remove reference to opbeat

---

test/test.js

I had a bug that made me think this was not working as expected, so I added these tests. But they pass, so I guess it works 😅

test: check that requests are not opened prematurely

---

README.md
index.js
lib/truncate.js
package.json
test/truncate.js

If not otherwise truncated, all strings should be chopped at 1024 characters.
Fixes: https://github.com/elastic/apm-agent-nodejs/issues/630

feat: ensure strings always truncated

---

README.md
index.js
lib/truncate.js
test/basic.js
test/lib/utils.js
test/truncate.js

This adds the `sendMetricSet` method.
~~Depends on #36.~~

feat: add sendMetricSet method

---

index.js

Fixed dynamic require call elastic/apm-nodejs-http-client#43

webpack dynamic require fixed

---

README.md
index.js
test/config.js

This is a prerequisite for fixing elastic/apm-agent-nodejs#688

feat: allow config options to be updated

---

README.md
index.js
test/config.js
test/lib/utils.js

This is the http client half of elastic/apm-agent-nodejs#963.

feat: support global labels

---

README.md
index.js
test/abort.js
test/basic.js
test/central-config.js
test/config.js
test/edge-cases.js
test/k8s.js
test/lib/utils.js
test/remote-config.js
test/side-effects.js
test/stringify.js
test/truncate.js

HTTP client part of https://github.com/elastic/apm-agent-nodejs/issues/1125.

feat: add support for APM Agent Configuration via Kibana

---

README.md
index.js

docs: describe what happens if no central config is set up

---

index.js
test/lib/utils.js

This is one of my first PR so any feedback is really appreciated
Fixes #72

feat: added nodejs runtime name and version to user-agent string

---

index.js
test/lib/utils.js

Depends on #81
When #81 lands, `master` just needs to be merged into this PR or the branch should be rebased.

refactor: use new URL parser

---

index.js
lib/truncate.js
package.json
test/basic.js
test/config.js
test/lib/utils.js
test/stringify.js

Depends on #82
When #82 lands, `master` just needs to be merged into this PR or the branch should be rebased.

chore(package): bump 'standard' linter to ^14.3.1

---

README.md
index.js
test/config.js

This is the http-client half of elastic/apm-agent-nodejs#1322.

feat(config): add serviceNodeName

---

lib/truncate.js
test/truncate.js

+ Depends on https://github.com/elastic/apm-agent-nodejs/pull/1685

feat: add destination fields to span context

---

.github/labeler-config.yml
.github/workflows/labeler.yml

This GitHub Workflow adds the "agent-nodejs" label to all new issues and pull requests

Added GitHub Workflow for auto-labeling

---

index.js

Nothing was using those callback args. Also clarify that an error from
getCloudMetadata is intentionally being ignored, and (lightly) log it.

refactor: _fetchAndEncodeMetadata to not callback with args

---

index.js

A small perf refactor. _writeBatch is an inner function which can be
a hotspot under high event load.

perf: eliminate encodeObject stack and faster loop in _writeBatch

---

.ci/jobs/apm-nodejs-http-client-mbp.yml
.ci/jobs/defaults.yml

Add minor change to configure the job itself with the project type

ci(jjbb): multibranch project in the job itself

---

index.js
test/basic.test.js

This refactors some internal vars for clarity. This will help reduce the diff for coming changes for https://github.com/elastic/apm-agent-nodejs/issues/2485

refactor: some internal vars for clarity

---

.github/workflows/opentelemetry.yml

Export GH action to OTEL traces
Help to observe our CICD process
Secrets have been created

action: opentelemetry

---

CHANGELOG.md
README.md
index.js
package.json
test/lambda-usage.test.js

Refs: https://github.com/elastic/apm-agent-nodejs/issues/3136

v11.4.0; support for pre-registering partial transactions for AWS Lambda
