README.md, index.js, test/test.js
This is useful for later doing benchmarks and potentially reporting the number of sent events to the APM Server as a metric. When we have settled on a response JSON format for the APM Server, we can record and expose the number of dropped events as well.
=> feat: add client.sent property

test/test.js
There was no reason to access the private `_chopper` object, when the `flush()` function does the same job. This even means that it uses the internal queueing of the writeable stream so that we don't have to delay the chop until after the `sendSpan` have finished.
=> test: simplify payloadLogFile test

index.js, test/lib/utils.js, test/test.js
Not sure how important this is, but I think it's better to store the "pure" version. This way it's also the same format as the `framework.version`, `version` and `agent.version`
=> fix: report node version not prefixed with 'v'

README.md, index.js, package.json, test/test.js
This fixes a bug where the max size of the HTTP body (750kb) was wrongly counted towards the uncompressed bytes. The new version of stream-chopper will count towards the compressed bytes instead.
=> refactor: use new chopper transform feature to gzip

index.js, test/abort.js, test/lib/utils.js
If the server responds before the client have ended the request, it means something didn't go as planned and the server have given up trying to process the request. It therefore doesn't serve any purpose to continue sending data to the server in that request and we should abort.
=> fix: abort current request if server responds early

lib/truncate.js
There was a bug in the context max length check that allowed it to have an `undefined` value for max.
=> fix(truncate): ensure context truncate has max

README.md, index.js, package.json, test/config.js
Read container info from `/proc/self/cgroup` to get docker container id and kubernetes pod id default values.
=> feat(options): get cgroups container info

index.js, lib/stringify.js, test/lib/utils.js, test/stringify.js
Normally headers will always be strings or array of strings, but in case they have been parsed upstream, we must make sure to stringify them here before sending them to the server.
=> fix: stringify header values

package.json
This fixes an issue with the Kubernetes container info not being reported automatically.
=> fix(package): bump container-info to v1.0.1

index.js, test/config.js, test/k8s.js
Previously the Kubernetes metadata was added to `meatadata.kubernetes`, but the APM Server expects it to be under `metadata.system.kubernetes`, so it was just silently dropped.
I took the liberty to limit the creation of hidden classes a bit while I was touching the code. It's not a hot code path, so it's not a big deal, but I thought I'd do it anyway.
=> fix: add kubernetes metadata correctly to payload

.ci/Jenkinsfile
- `master` worker could be used but causes bottlenecks in some cases.
- This will allow to use of another worker and get rid of any potential bottlenecks when the build queue is massive.
=> ci(jenkins): avoid builds in the master worker

index.js
This ensures the cork timer is cleared when the stream is destroyed.
=> fix: cork timer should be cleared on destroy

index.js
If running Node.js 10.2.0 or newer, a race condition would occur in the following scenarios that would leave the stream permanently corked:
- Call `flush` while the stream is corked and `bufferWindowTime !== -1`
- Call `sendSpan`, `sendTransaction`, `sendError`, or `sendMetricSet` while stream is corked, `bufferWindowTime === -1` and `_writableState.length >= bufferWindowSize`.
=> fix: race-condition that could leave stream in corked state

test/side-effects.js
If running `tape test/*.js`, the tests inside `test/side-effects.js` would run just fine. But when running the file directly, either via `tape test/side-effects.js` or `node test/side-effects.js`, the tests would fail because of a race-condition.
The race-condition meant that the order of the callback calls would be different. By omitting the `t.end()` call and relying on the `t.plan()` call instead, we get around this issue.
=> test: allow test/side-effects.js to be run stand-alone

index.js
Rather than using reduce and string concatentation, which creates many intermediary strings, use map and join instead which only creates an intermediary array and a single string allocation
This _may_ fix PR #80.
=> feat: improve writev encoding performance

.ci/Jenkinsfile, .ci/jobs/apm-nodejs-http-client-mbp.yml, .ci/jobs/apm-nodejs-http-client-schedule-daily.yml, .ci/jobs/defaults.yml, .ci/schedule-daily.groovy
- Build on a daily basis the pipeline for the master branch.
- PRs and tags don't run on a daily basis but on a push basis.
- Optimize the number of required agents, as it will reuse the top-level one.
=> ci(jenkins): run master on daily basis

.ci/Jenkinsfile
we will use withENv to change the HOME environment variable to avoid affect other parallels steps
related to https://github.com/elastic/apm-nodejs-http-client/issues/94
=> ci(jenkins): encapsulate environment changes

lib/truncate.js, test/truncate.js
This fixes a bug introduced in #92.
=> fix(truncate): nulls should not be treated as objects

README.md, index.js, package.json, test/config.js, test/lib/utils.js
We add support for specifying the CA certificate
for verifying the server's TLS certificate chain.
Update the tests to use a self-signed certificate
that is valid for "localhost", rather than the
one generated by selfsigned, which is valid for
"example.org". This certificate also has a much
longer expiry time, which avoids having to reinstall
http-pem after a year.
This is in support of https://github.com/elastic/apm-agent-nodejs/issues/1508
=> Add serverCaCert option

index.js, lib/container-info.js, test/k8s.js
Moves https://github.com/elastic/apm-agent-nodejs/issues/1821 forward.
This PR ensure the podID we extract from cgroups info [conforms to the following spec change](https://github.com/elastic/apm/pull/344/files).
This change is made here instead of the `container-info` package.  The `container-info` package is in used outside of elastic, and changing its behavior would impact multiple parties.  Instead we rely on this package to grab the container information, and then add a new module for making any additional changes required locally. 
Once this lands we'll need to do a release of `apm-nodejs-http-client`.  So long as the semver bump is patch or minor, we shouldn't need a version bump in the agent proper (it's [using `^9.4`](https://github.com/elastic/apm-agent-nodejs/blob/3a845efe2fc327 …
=> feat: ensure podId conforms to naming conventions

README.md, index.js, test/config.js
This would allow the apm-agent-nodejs to be used with api keys not only secret tokens.
=> Support api keys for authentication

.npmignore, package.json
before:
```
% npm publish --dry-run
npm notice
npm notice 📦  elastic-apm-http-client@9.4.1
npm notice === Tarball Contents ===
npm notice 1.1kB  LICENSE
npm notice 527B   lib/container-info.js
npm notice 22.4kB index.js
npm notice 280B   lib/ndjson.js
npm notice 7.4kB  lib/truncate.js
npm notice 1.3kB  package.json
npm notice 12.2kB README.md
npm notice 68B    .github/labeler-config.yml
npm notice 350B   .github/workflows/labeler.yml
npm notice === Tarball Details ===
npm notice name:          elastic-apm-http-client
npm notice version:       9.4.1
npm notice package size:  13.8 kB
npm notice unpacked size: 45.6 kB
npm notice shasum:        8c8990ea6172fb0b5910b2532e5958e894cb4209
npm notice integrity:     sha512-w+UaLo9w6BFed[...]BxlIHwX/XJQ8Q==
npm notice total files:   9
npm notice
+ …
```
=> chore: prefer 'files' to .npmignore to control published files

index.js, lib/truncate.js, test/config.js, test/truncate.js
This is the HTTP client portion of https://github.com/elastic/apm-agent-nodejs/issues/1815
This PR
1. Adds a new top level `cloudMetadata` configuration field to the configuration options
2. Passes this data on to the `cloud` key of the metadata payload that's sent to APM server
3. Implements truncation rules, following the pattern set for other metadata fields
This PR treats the client as a dumb pipe and does not make heroic efforts to validate the data, (other than truncating too long data, as #3)
Spec: https://github.com/elastic/apm/blob/3f224a9cbacb196bbb196b0868d9fa90a0bbaf6c/specs/agents/metadata.md#cloud-provider-metadata
Schema: https://github.com/elastic/apm-server/blob/master/docs/spec/v2/metadata.json
=> Accept Cloud Metadata Payload

index.js, test/edge-cases.js
req.abort() is deprecated since v14.1.0/v13.14.0 and it's recommended to
use req.destroy() instead.
This also allows us to provide a custom error message, which means we
can know when a socket is closed based an external factor vs. when we
close it ourselves internally.
=> fix: destroy request instead of aborting it on timeout

index.js, test/basic.js, test/edge-cases.js, test/writev.js
If the client was .destroy()d before cloud metadata fetching was
complete then the unconditional `.uncork()` in the fetching callback
could result in writing to the stream. Using `.maybeUncork()` uses the
explicit guard to not uncork if the stream is destroyed.
In apm-agent-nodejs tests I was observing this error in the apm-server client
at the end of some tests:
```
APM Server transport error: Error: Cannot call write after a stream was destroyed
at doWrite (/Users/trentm/el/apm-agent-nodejs2/node_modules/readable-stream/lib/_stream_writable.js:409:38)
at clearBuffer (/Users/trentm/el/apm-agent-nodejs2/node_modules/readable-stream/lib/_stream_writable.js:526:7)
at Client.Writable.uncork (/Users/trentm/el/apm-agent-nodejs2/node_modules/readable-stream/lib/_stream_writable.js:321:94)
at …
```
=> fix: possible write after .destroy() if destroyed before metadata fetch

index.js, test/edge-cases.js
Before this change calling client.sendTransaction() et al after
client.destroy() would stage the data to be written, then set the
_corkTimer timeout, after which it would uncork the stream and attempt
to write:
Error: Cannot call write after a stream was destroyed
=> fix: calling client.send*() after client.destroy() should not error

.gitignore, CHANGELOG.md, index.js, test/config.js
This will ultimately fix https://github.com/elastic/apm-agent-nodejs/issues/1749 when that repo is updated to use a new release of this package.
https://github.com/elastic/apm-agent-nodejs/issues/1749#issuecomment-782470960 best describes the issue.
The fix here is to not call `res.destroy(err)` on a res that we have already completed (even if it wasn't a 200 response, it was still a successfully completed response). To keep the fix targetted and small, this PR **does not** fix the issue with the keep-alive agent only being used after a second `client.config(...)` call. I'll open a separate PR for that work.
=> fix: crash on error polling config with node v12 and keep-alive agent

.gitignore, .npmrc
Also:
- anchors some .gitignore'd files to the root dir
- drops the "target" .gitignore because I don't know what that is meant to be from
=> chore: disallow package-lock.json file generation

CHANGELOG.md, README.md, index.js, test/abort.js, test/basic.js, test/central-config.js, test/config.js, test/edge-cases.js, test/k8s.js, test/lib/utils.js, test/stringify.js, test/truncate.js
(This is a follow up on and depends on #138 going in first.)
Fix config initialization such that the keep-alive agent is used all the
time as intended. Before this change the keep-alive HTTP(S) agent would
only be used if a second call to `client.config(...)` was made. For
the Elastic APM Agent's usage of this module, that was when any of the
express, fastify, restify, hapi, or koa modules was instrumented.
- the creation of the HTTP(S) agent (this._agent) is moved into `Client.prototype.config` -- along with setting of `this._transport` for convenience.
- As a minor side note the setting of _transport is taking the simplification from https://github.com/elastic/apm-nodejs-http-client/pull/125/files
- The calls to `Writable.call()` and `new _transport.Agent()` have been cleaned up to only …
=> fix: ensure keep-alive HTTP(S) agent is used

README.md, index.js, lib/logging.js
1. This adds a `logger` option to the client, which expects a pino logger. If not given, a "no-op" logger will be used to stay silent. This logger is documented to be for trace and debug-level logging only, i.e. nothing about logging for the user of this apmclient or the apm agent using this lib.
2. This collects some internal stats on elapsed times on the "_write*" functions where the sync delays are. Also a private `_getStats()` is added that can be used by dev/debugging scripts to dump info under load tests.
The matching APM agent PR is: https://github.com/elastic/apm-agent-nodejs/pull/2015
* * *
This is pre-support for a coming PR to fix https://github.com/elastic/apm-nodejs-http-client/issues/136
I'm trying to separate out some changes to make that change more focused.
=> add optional pino logger and collection of internal stats

package.json
Because of https://github.com/codecov/codecov-node/issues/284 codecov
reporting is sometimes failing. With the new default node v15 option
of '--unhandled-rejections=strict', this results in the occasional
non-zero exit status, which breaks our node v15 builds. This changes to
ignore that exit status.
=> fix: ignore codecov.io reporting failure

CHANGELOG.md, index.js, test/edge-cases.js, test/lib/call-me-back-maybe.js
Fixes: #150
Explanation of the issue and fix is on #150.
=> fix: ensure client.flush(cb) callback is called when no active handles

CHANGELOG.md, README.md, index.js, package.json, test/basic.js, test/metadata-filter.js
A facility to custom filter the "metadata" object sent to APM server at
the start of every intake request.
This refactors setting of `_encodedMetadata` to happen in only one
place (`_resetEncodedMetadata`), so that it can apply the metadata
filters in only on place.
Refs: https://github.com/elastic/apm-agent-nodejs/issues/1916
=> feat: client.addMetadataFilter(fn)

.ci/Jenkinsfile, .ci/scripts/test.sh, .codecov.yml, .github/workflows/test.yml, .gitignore, README.md, package.json
After some discussion, it was agreed we aren't getting utility out of
uploading coverage info to codecov.io. We still have a coverage report
from 'npm test'.
=> chore: drop codecov.io usage

index.js, test/config.js
This http-client _conf.cloudMetadata was a part of #126 that was
ultimately not used. It was replaced with _conf.cloudMetadataFetcher
in #129.
=> chore: drop obsolete opts.cloudMetadata from earlier impl

CHANGELOG.md, index.js, package.json
Use uninstrumented https.request() et al (grabbing references before the
agent does shimming) for requests to APM server. This avoids them
interfering in tracing (adding trace-context headers to APM server
requests, emitting debug logs about spans). This will fix
https://github.com/elastic/apm-agent-nodejs/issues/1995
=> fix: do not trace APM server client requests

CHANGELOG.md, README.md, index.js, lib/truncate.js, package.json, test/truncate.js
- Truncate on number of chars, not bytes. The "maxLength" values in json schema (for the intake API) are [intended to be in JSON characters](https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.6.3.1), i.e. unicode chars -- so this is a valid change. Truncating on chars (`str.length` check) is also *much* faster than the `unicode-byte-truncate` algorithm was.
- Remove truncateQueriesAt, add truncateLongFieldsAt which covers that
and the other fields specified for [`long_field_max_length`](https://github.com/elastic/apm/blob/master/specs/agents/field-limits.md#long_field_max_length-configuration).
- Deprecate truncateErrorMessagesAt. If unspecified, the
truncateLongFieldsAt value will be used.
BREAKING CHANGE. This "breaking" is for the http-client's API because …
=> feat: truncation changes

CHANGELOG.md, README.md, index.js, package.json, test/basic.test.js, test/edge-cases.test.js, test/expectExtraMetadata.test.js, test/writev.test.js
These provide a mechanism for the Node.js APM Agent to pass in metadata
asynchronously and be sure that the client will not begin an intake
request until that metadata is provided.
Refs: https://github.com/elastic/apm-agent-nodejs/issues/2404
=> 10.3.0; expectExtraMetadata config & Client#setExtraMetadata

CHANGELOG.md, README.md, index.js, package.json, test/abort.test.js, test/apm-server-version.test.js, test/basic.test.js, test/central-config.test.js, test/config.test.js, test/edge-cases.test.js, test/expectExtraMetadata.test.js, test/k8s.test.js, test/lib/call-me-back-maybe.js, test/lib/utils.js, test/metadata-filter.test.js, test/side-effects.test.js, test/stringify.test.js, test/truncate.test.js, test/writev.test.js
This is to support the Node.js APM agent changing its behaviour based on
the APM Server version. Specifically whether to send or drop unsampled
transactions.
Refs: https://github.com/elastic/apm-agent-nodejs/issues/2455
=> feat: Add APM Server version fetching and client.supportsKeepingUnsampledTransaction()

CHANGELOG.md, README.md, index.js, lib/logging.js, package.json, test/basic.test.js, test/lambda-usage.test.js, test/run_tests.sh
This adds 'Client#lambdaStart()' and the 'lambdaEnd: true' option to
'Client#flush([opts,] [cb])' to support for flushing Lambda invocation
tracing data and signaling the Elastic Lambda extension per spec.
https://github.com/elastic/apm/blob/main/specs/agents/tracing-instrumentation-aws-lambda.md#data-flushing
Refs: https://github.com/elastic/apm-agent-nodejs/issues/2485
=> feat: add support for Lambda data flushing

CHANGELOG.md, index.js
Doing the back-off in a Lambda env can result in the APM agent instrumentation *breaking* the Lambda function response: https://github.com/elastic/apm-agent-nodejs/issues/2598
See the inline comment and the motivation at: https://github.com/elastic/apm/pull/613
```
fix: do not back-off on intake req errors in Lambda env
Refs: https://github.com/elastic/apm-agent-nodejs/issues/2598
Refs: https://github.com/elastic/apm/pull/613
```
=> fix: do not back-off on intake req errors in Lambda env

.github/workflows/test.yml, test/config.test.js, test/run_tests.sh
The `run_tests.sh` bash script would always exit with a code of `0`, even if one of the test files had `not ok` tests.  This meant that the test failures were not picked up by CI.  
This PR changes that script to ensure we exit with a `0` if all test suites ran `ok`, or exit with the last failure code seen.
This PR also bumps the GitHub actions versions tested to include Node.js 18, and fixes a small test fixture issue with some changed output in Node 18.
=> fix: ensure run_tests.sh exits with non zero code when there's a test error

CHANGELOG.md, index.js, lib/central-config.js, test/central-config.test.js
Refs: https://github.com/elastic/apm-agent-nodejs/issues/2941
The [spec change](https://github.com/elastic/apm/pull/667/files) requires a minimum 5s delay for refetching central config. The Node.js APM agent didn't have the "spin loop fetching central config from `Cache-Control: max-age=0`" issue. However, theoretically a *large* max-age value could overflow the max `setTimeout` delay (https://developer.mozilla.org/en-US/docs/Web/API/setTimeout#maximum_delay_value) which could result in a similar spin loop. I picked a maximum value of 1 day -- a large enough value that I cannot imagine it getting in a way of a legitimate max-age value from the APM server.
It might be worth adding a max guard to the spec.
=> fix: put [5s, 1d] range guard on the delay before re-fetching central config

CHANGELOG.md, index.js, lib/central-config.js, package.json, test/central-config.test.js
If a central config request does not receive a Cache-Control response
header with a `max-age` field, then it incorrectly results in `NaN` for
the interval for the next central config fetch.
Refs: https://github.com/elastic/apm-agent-nodejs/issues/3029
=> fix: Prevent a possible tight loop in central config fetching.

CHANGELOG.md, README.md, index.js, package.json
The APM agent won't *require* this change, because in the referenced
change it will be adding the same default on its end.
Refs: https://github.com/elastic/apm-agent-nodejs/pull/3049
=> fix: change default APM server_url to 'http://127.0.0.1:8200' to avoid IPv6 ambiguity

.github/workflows/lint.yml, Makefile, package.json, test/run_tests.sh
Separate 'lint' and 'test'. Add testing of node v19.
=> chore: add 'make cutarelease' and other dev conveniences

CHANGELOG.md, README.md, index.js, package.json, test/extraMetadata.test.js
This is a way to provide additional metadata that is merged into the
metadata object created from the other individual config options. This
is similar to `expectExtraMetadata: true` && `setExtraMetadata(...)`,
but is a way to provide the metadata *synchronously*.
Refs: https://github.com/elastic/apm-agent-nodejs/pull/3071
* * *
This'll be used for the Azure Functions work. Like Lambda instrumentation, some extra metadata is provided separate from the "cloud metadata fetcher" mechanism. However, unlike Lambda we can do this synchronously without needing to way for the first Function invocation because all data we need is in the environment
=> feat: add 'extraMetadata' config option

CHANGELOG.md, README.md, index.js, package.json, test/config.test.js
This adds 'metadata.service.agent.activation_method' if the optional
config var is provided. Bump to v11.2.0.
Refs: https://github.com/elastic/apm-agent-nodejs/issues/3039
=> feat: add an 'agentActivationMethod' config var

CHANGELOG.md, README.md, index.js, package.json, test/apm-server-version.test.js, test/config.test.js
Refs: https://github.com/elastic/apm-agent-nodejs/issues/3230
Refs: https://github.com/elastic/apm/pull/780
=> v11.3.0; send activation_method metadata only to APM server v8.7.1 or later

CHANGELOG.md, README.md, index.js, package.json, test/apm-server-version.test.js
Optimistically assume the APM server version is not v8.7.0. This allows
typically avoiding the v8.7.0 bug (which isn't that severe) with still
sending the `activation_method` for intake requests before the APM
server version fetch completes -- e.g. for fast first serverless
invocations.
Refs: https://github.com/elastic/apm/issues/781
=> v11.3.1; default to sending `activation_method` field if APM server version is not (yet) known
